name: go

on:
  push:
    paths:
      - go/**
      - .github/workflows/go.yml
  pull_request:
    paths:
      - go/**
      - .github/workflows/go.yml

defaults:
  run:
    working-directory: go

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ["1.21", "stable"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
      - run: test -z "$(gofmt -l .)"
      - run: go vet ./...
      - run: go test -race ./...
